import 'models.dart';

const governoratesAr = [
  'بغداد',
  'البصرة',
  'النجف',
  'كربلاء',
  'أربيل',
  'السليمانية',
  'دهوك',
  'نينوى',
  'ذي قار',
  'ميسان',
  'واسط',
  'بابل',
  'ديالى',
  'كركوك',
  'الأنبار',
  'صلاح الدين',
  'القادسية',
  'المثنى',
];

const governoratesEn = [
  'Baghdad',
  'Basra',
  'Najaf',
  'Karbala',
  'Erbil',
  'Sulaymaniyah',
  'Duhok',
  'Nineveh',
  'Dhi Qar',
  'Maysan',
  'Wasit',
  'Babil',
  'Diyala',
  'Kirkuk',
  'Anbar',
  'Salah al-Din',
  'Al-Qadisiyah',
  'Al-Muthanna',
];

const hotels = <Hotel>[
  Hotel(
    id: 'baghdad-1',
    nameAr: 'فندق دجلة رويال',
    nameEn: 'Tigris Royal Hotel',
    governorateAr: 'بغداد',
    governorateEn: 'Baghdad',
    addressAr: 'الكرادة - بغداد',
    addressEn: 'Karrada - Baghdad',
    rating: 4.6,
    descriptionAr: 'فندق عصري في قلب بغداد مناسب لرحلات العمل والعائلة.',
    descriptionEn:
        'A modern hotel in central Baghdad for business and family stays.',
    amenitiesAr: ['واي فاي', 'موقف سيارات', 'مطعم', 'استقبال 24 ساعة'],
    amenitiesEn: ['Wi-Fi', 'Parking', 'Restaurant', '24h reception'],
    latitude: 33.3128,
    longitude: 44.3615,
    rooms: [
      Room(
          id: 'b1-r1',
          nameAr: 'غرفة ديلوكس',
          nameEn: 'Deluxe Room',
          capacity: 2,
          bedsAr: 'سرير مزدوج',
          bedsEn: '1 double bed',
          price: 125000,
          available: true),
      Room(
          id: 'b1-r2',
          nameAr: 'جناح عائلي',
          nameEn: 'Family Suite',
          capacity: 4,
          bedsAr: 'سريران',
          bedsEn: '2 beds',
          price: 190000,
          available: true),
    ],
  ),
  Hotel(
    id: 'basra-1',
    nameAr: 'فندق شط العرب',
    nameEn: 'Shatt Al-Arab Hotel',
    governorateAr: 'البصرة',
    governorateEn: 'Basra',
    addressAr: 'العشار - البصرة',
    addressEn: 'Al-Ashar - Basra',
    rating: 4.4,
    descriptionAr: 'إقامة مريحة بموقع قريب من مركز البصرة.',
    descriptionEn: 'Comfortable stay close to central Basra.',
    amenitiesAr: ['واي فاي', 'موقف سيارات', 'مطعم', 'خدمة غرف'],
    amenitiesEn: ['Wi-Fi', 'Parking', 'Restaurant', 'Room service'],
    latitude: 30.5085,
    longitude: 47.7804,
    rooms: [
      Room(
          id: 'ba-r1',
          nameAr: 'غرفة قياسية',
          nameEn: 'Standard Room',
          capacity: 2,
          bedsAr: 'سريران مفردان',
          bedsEn: '2 single beds',
          price: 95000,
          available: true),
      Room(
          id: 'ba-r2',
          nameAr: 'جناح تنفيذي',
          nameEn: 'Executive Suite',
          capacity: 3,
          bedsAr: 'سرير مزدوج وأريكة',
          bedsEn: 'Double bed + sofa',
          price: 165000,
          available: true),
    ],
  ),
  Hotel(
    id: 'najaf-1',
    nameAr: 'فندق الروضة',
    nameEn: 'Al Rawda Hotel',
    governorateAr: 'النجف',
    governorateEn: 'Najaf',
    addressAr: 'المدينة القديمة - النجف',
    addressEn: 'Old City - Najaf',
    rating: 4.5,
    descriptionAr: 'فندق قريب من مركز المدينة مع غرف عائلية.',
    descriptionEn: 'A central hotel with family-friendly rooms.',
    amenitiesAr: ['واي فاي', 'مطعم', 'مصعد', 'استقبال 24 ساعة'],
    amenitiesEn: ['Wi-Fi', 'Restaurant', 'Elevator', '24h reception'],
    latitude: 32.0000,
    longitude: 44.3350,
    rooms: [
      Room(
          id: 'n-r1',
          nameAr: 'غرفة مزدوجة',
          nameEn: 'Double Room',
          capacity: 2,
          bedsAr: 'سرير مزدوج',
          bedsEn: 'Double bed',
          price: 85000,
          available: true),
      Room(
          id: 'n-r2',
          nameAr: 'غرفة عائلية',
          nameEn: 'Family Room',
          capacity: 5,
          bedsAr: 'ثلاثة أسرّة',
          bedsEn: '3 beds',
          price: 140000,
          available: true),
    ],
  ),
  Hotel(
    id: 'erbil-1',
    nameAr: 'فندق القلعة جراند',
    nameEn: 'Citadel Grand Hotel',
    governorateAr: 'أربيل',
    governorateEn: 'Erbil',
    addressAr: 'عنكاوا - أربيل',
    addressEn: 'Ankawa - Erbil',
    rating: 4.7,
    descriptionAr: 'فندق أنيق بخدمات متميزة وقرب من أبرز مناطق أربيل.',
    descriptionEn: 'Elegant hotel near major Erbil attractions.',
    amenitiesAr: ['واي فاي', 'موقف سيارات', 'مطعم', 'نادي رياضي'],
    amenitiesEn: ['Wi-Fi', 'Parking', 'Restaurant', 'Gym'],
    latitude: 36.2063,
    longitude: 44.0089,
    rooms: [
      Room(
          id: 'e-r1',
          nameAr: 'غرفة بريميوم',
          nameEn: 'Premium Room',
          capacity: 2,
          bedsAr: 'سرير كينغ',
          bedsEn: 'King bed',
          price: 155000,
          available: true),
      Room(
          id: 'e-r2',
          nameAr: 'جناح جراند',
          nameEn: 'Grand Suite',
          capacity: 4,
          bedsAr: 'سرير كينغ وأريكة',
          bedsEn: 'King bed + sofa',
          price: 245000,
          available: true),
    ],
  ),
];

const destinations = <Destination>[
  Destination(
      nameAr: 'أهوار الجبايش',
      nameEn: 'Chibayish Marshes',
      governorateAr: 'ذي قار',
      governorateEn: 'Dhi Qar',
      descriptionAr: 'منطقة طبيعية فريدة ضمن أهوار جنوب العراق.',
      descriptionEn:
          'A unique natural landscape in the marshes of southern Iraq.'),
  Destination(
      nameAr: 'قلعة أربيل',
      nameEn: 'Erbil Citadel',
      governorateAr: 'أربيل',
      governorateEn: 'Erbil',
      descriptionAr: 'معلم تاريخي بارز في قلب مدينة أربيل.',
      descriptionEn: 'A landmark historic citadel in the heart of Erbil.'),
  Destination(
      nameAr: 'زقورة أور',
      nameEn: 'Ziggurat of Ur',
      governorateAr: 'ذي قار',
      governorateEn: 'Dhi Qar',
      descriptionAr: 'موقع أثري سومري شهير قرب الناصرية.',
      descriptionEn: 'A renowned Sumerian archaeological site near Nasiriyah.'),
];
